export enum LayerColor {
  aqua = 'aqua',
  black = 'black',
  blue = 'blue',
  fuchsia = 'fuchsia',
  green = 'green',
  gray = 'gray',
  lime = 'lime',
  maroon = 'maroon',
  navy = 'navy',
  olive = 'olive',
  orange = 'orange',
  purple = 'purple',
  red = 'red',
  silver = 'silver',
  teal = 'teal',
  white = 'white',
  yellow = 'yellow',
}
